### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/ProgenWebInterface#4]
Make the pwi style Mobile Friendly.

Systems:
Android
IOS
Windows

**Comment by HGotthard** [comment]
https://github.com/Progen-Dev/ProgenWebInterface/blob/4dde4640e081c4d6dc0dd97d6245976b02ac88e9/src/App.vue#L4

replace with `<div class="columns is-desktop">`

**Comment by ShowMeYourSkil** [comment]
The webinterface is now mobile friendly
